import json

from flask import Flask, render_template, request
from troposphere import Parameter, Ref, Tags, Template
from troposphere.ec2 import VPC, Subnet

app = Flask(__name__)


@app.route('/')
def main_page():
    return app.send_static_file('index.html')


@app.route('/api/create', methods=['POST'])
def readjson():
    t = Template()
    t.add_version('2010-09-09')
    t.add_description("AWS Cloudformation VPC")
    data = json.loads(request.data)
    vpc_cidr_param = t.add_parameter(
        Parameter('VPCCidr',
                  Type='String',
                  Default=data['vpccidr']
                  )
    )
    vpc = t.add_resource(
        VPC(
            "VPC",
            CidrBlock=Ref(vpc_cidr_param),
            Tags=Tags(Created="Generated by Nephelae")

        )
    )

    for index, subnet in enumerate(data['subnets']):
        print(subnet, "ZACH")
        t.add_parameter(
            Parameter('SubnetCidrBlock{}'.format(index),
                      Type='String',
                      Default=subnet['cidr'])
        )

        t.add_resource(
            Subnet(
                'Subnet{}'.format(index),
                MapPublicIpOnLaunch=subnet['public'],
                CidrBlock=subnet['cidr'],
                VpcId=Ref(vpc),
                Tags=Tags(Created="Generated by Nephelae")
            )
        )

    return t.to_json(), 200
